name: Scrape Events Daily

on:
  schedule:
    # Run daily at 8:00 AM EST (13:00 UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Updated to Node.js 20 to fix File API issue

      - name: Install dependencies
        run: npm install

      - name: Run dynamic scraper
        env:
          POCKETBASE_URL: ${{ secrets.POCKETBASE_URL }}
          POCKETBASE_ADMIN_EMAIL: ${{ secrets.POCKETBASE_ADMIN_EMAIL }}
          POCKETBASE_ADMIN_PASSWORD: ${{ secrets.POCKETBASE_ADMIN_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: node scrape-all-organizations.js

      - name: Report results
        if: always()
        run: echo "Scraping job completed"
